name = "eskuvo-upload"
main = "index.js"
compatibility_date = "2024-01-01"

# Development environment
[env.development]
vars = { DRIVE_FOLDER_ID = "root" }

# Production environment
[env.production]
vars = { DRIVE_FOLDER_ID = "1CcpN3MUtGl6OS49gH7_9mE4nHn4vX1ea" }

# Development
[dev]
port = 8787
local_protocol = "http"
